#!/bin/sh

#
# Javadoc generation batch file
#
# Untested!!!!
#

echo "Starting URI Javadoc Generation"

# The place that you want the javadoc deposited
DEST_DIR=./docs/javadoc

TITLE="URI Development Library"

# The location of your JDK core libraries javadoc. This is for linking against
# all the java.net stuff. If you don't want this then leave it blank
JDK_JAVADOC="file:/usr/local/java/javadoc/jdk1.3/api/"

LOCAL_CLASSPATH=src:lib/gnu_regexp.jar:lib/httpclient.jar

FLAGS="-version -overview src/overview.html"

if [ -f ${DEST_DIR}/index.html ]; then
  echo "Old Javadocs found - removing them"
  rm -fr ${DEST_DIR}/*
fi

if [ -z ${JDK_JAVADOC} ]; then
  FLAGS="${FLAGS} -link ${JDK_JAVADOC}"
fi

javadoc ${FLAGS}  -windowtitle "${TITLE}" -classpath ${LOCAL_CLASSPATH}\
        -d ${DEST_DIR} \@src/package-list

#
# REM Wait for the user to confirm
#

echo "Done"
