#!/bin/sh
#
# A script to create a JAR file for a specific version
#

if (( $# < 1 )) ; then
  echo "Usage: make_jar version_number"
  exit 1
fi

JAR_FILE=uri-$1.jar

cd src

if [ -f ${JAR_FILE} ]; then
  echo "Old JAR file found. Removing"
  rm -f ${JAR_FILE}
fi


echo "Creating file: ${JAR_FILE}"
jar cvf ${JAR_FILE} org vlc

cd ..

mv src/${JAR_FILE} .
echo "Done"
