#*********************************************************************
#
#  (C) 2001 The Virtual Light Company
#        http://www.vlc.com.au/
# 
# Package makefile for the vlc.net.resolve.thttp directory
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = vlc.net.resolve.thttp

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = \
  ResourceDescriptor.java \
  NamespaceResolver.java \
  FileParser.java \
  Resolver.java

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 

include ${PROJECT_ROOT}/make/Makefile.jav
