#*********************************************************************
#
#  (C) 2001 The Virtual Light Company
#        http://www.vlc.com.au/
# 
# Package makefile for the vlc.net.protocol.https directory
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = vlc.net.protocol.https

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = HttpsConnection.java \
	Handler.java

JARS_3RDPARTY = httpclient.jar

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 

include ${PROJECT_ROOT}/make/Makefile.jav
