#*********************************************************************
#
#  (C) 2001 The Virtual Light Company
#        http://www.vlc.com.au/
# 
# Package makefile for the org.ietf.uri.event directory
#
# Author: Justin Couch
# Version: $Revision: 1.1 $
#
#*********************************************************************

PACKAGE = org.ietf.uri.event

# The source files to compile. These are declared in order that they must be
# compiled in
SOURCE = ProgressEvent.java \
	ProgressListener.java \
	ProgressAdaptor.java \
	ProgressListenerMulticaster.java 

# The list of other files we need to copy from this directory to the classes
# directory when we are making JAR files.
EXTRA = 

include ${PROJECT_ROOT}/make/Makefile.jav
