#*********************************************************************
#
#  (C) 2001 The Virtual Light Company
#        http://www.vlc.com.au/
# 
# Package makefile for the org.ietf.uri.event directory
#
# Author: Justin Couch
# Version: $Revision: 1.3 $
#
#*********************************************************************

PACKAGES = \
  org.ietf.uri.resolve \
  org.ietf.uri.event \
  org.ietf.uri \
  vlc.net.content.text \
  vlc.net.content.x_java \
  vlc.net.resolve.file \
  vlc.net.resolve.thttp \
  vlc.net.protocol.data \
  vlc.net.protocol.file \
  vlc.net.protocol.http \
  vlc.net.protocol.https \
  vlc.net.protocol.shttp \
  vlc.net.protocol.jar 

NODOC_PACKAGES = \

JARS = uri.jar vlc_uri.jar

JARS_3RDPARTY= httpclient.jar gnu-regexp.jar

MAIN_CLASS     = 
MAIN_PACKAGE   = 
MAIN_JAR       = uri.jar

#*********************************************************************
#
# Javadoc
#
#*********************************************************************

OVERVIEW    = overview.html
WINDOWTITLE = 'URI Class Library Specification'
DOCTITLE    = 'URI Classes API'
HEADER      = 'URI Classes API'
BOTTOM      = '<center><font size=2>Copyright &copy; 1999 - 2001 \
		       <a href=\"http://www.vlc.com.au\">The Virtual Light Company</a> \
               </font></center>'

include $(PROJECT_ROOT)/make/Makefile.jav 
