#*********************************************************************
#
#  (C) 2000 Geotecnical Software Services - GeoSoft
# 
#*********************************************************************

PACKAGES = org.ietf.uri \
  org.ietf.uri.resolve \
  org.ietf.uri.event \ 
  vlc.net.content.text \
  vlc.net.content.x_java \
  vlc.net.resolve.file \
  vlc.net.resolve.thttp \
  vlc.net.protocol.data \
  vlc.net.protocol.file \
  vlc.net.protocol.http \
  vlc.net.protocol.https \
  vlc.net.protocol.shttp \
  vlc.net.protocol.jar 

NODOC_PACKAGES = \

JARS = uri.jar vlc_uri.jar

JARS_3RDPARTY= httpclient.jar gnu_regexp.jar

MAIN_CLASS     = 
MAIN_PACKAGE   = 
MAIN_JAR       = uri.jar

#*********************************************************************
#
# Javadoc
#
#*********************************************************************

WINDOWTITLE = 'URI Class Library Specification'
DOCTITLE    = 'URI Classes API'
HEADER      = 'URI Classes API'
BOTTOM      = '<center><font size=2>Copyright &copy; 2000 - \
		       <a href=\"http://www.vlc.com.au\">The Virtual Light Company</a> \
               </font></center>'

include $(PROJECT_ROOT)/make/Makefile.java 
